FROM python:3.11.11

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

# update pip globally within the container
RUN python3 -m pip install --upgrade pip
# update requirements by directory
RUN python3 -m pip install -r requirements.txt

CMD [ "bash", "run.sh" ]